### ISSUE TITLE
FR: Added use of tab to jump out of the color area

### ISSUE THREAD

**Issue by YIRU69** [Superschnizel/obisdian-fast-text-color#1]
Thank you very much for creating this useful plugin.

I found a problem when using the plugin. After creating the color area, I finished typing some text, can I quickly jump out of the color area? Like using the tab key?

**Comment by YIRU69** [comment]
Another suggestion is to cancel the prompt in the upper right corner（or add switch in setting）. Because it was found that the custom background color and font mismatch will cause the text to be invisible.

**Comment by YIRU69** [comment]
Another suggestion is that custom colors can be arranged as independent commands so that they can be used with other plug-ins.

**Comment by Superschnizel** [comment]
> Thank you very much for creating this useful plugin.
> 
> I found a problem when using the plugin. After creating the color area, I finished typing some text, can I quickly jump out of the color area? Like using the tab key?

This should be doable, i will see if i can get it done soon.



> Another suggestion is to cancel the prompt in the upper right corner（or add switch in setting）. Because it was found that the custom background color and font mismatch will cause the text to be invisible.

Can you elaborate on this problem? I dont think i quite understand what you mean. You can also create another Issue with the feature request tag.



> Another suggestion is that custom colors can be arranged as independent commands so that they can be used with other plug-ins.

This should also be Possible, i will add it to the backlog

**Comment by Superschnizel** [comment]
This is added in Version 0.1.6. You can try it out and give me feedback if it works as you imagine.

**Comment by YIRU69** [comment]
> The ability to tabout was added in Version 0.1.6. You can try it out and give me feedback if it works as you imagine.
![screenshots](https://github.com/Superschnizel/obisdian-fast-text-color/assets/48148292/16187bcd-6cb4-4fd7-af71-9c19c955e8dd)

It not work.

> Can you elaborate on this problem? I dont think i quite understand what you mean. You can also create another Issue with the feature request tag.

![PixPin_2024-04-12_08-39-47](https://github.com/Superschnizel/obisdian-fast-text-color/assets/48148292/dce08114-4635-47aa-8ec2-7bf864598739)

**Comment by Superschnizel** [comment]
Are you on the newest Version (0.1.6)?

**Comment by YIRU69** [comment]
On version 0.1.6. I test it on default.

**Comment by Superschnizel** [comment]
Great! Please tell me if there ever is another issue.
