### ISSUE TITLE
Fast color plugin interfers with AnuPpcin theme and changes the background color. 

### ISSUE THREAD

**Issue by amatya-aditya** [Superschnizel/obisdian-fast-text-color#10]
**Without Fast Color Plugin**

![image](https://github.com/Superschnizel/obisdian-fast-text-color/assets/63241408/6a594caa-87fb-4e69-a31e-335f8ba1589a)

**With Fast Color Plugin**

![image](https://github.com/Superschnizel/obisdian-fast-text-color/assets/63241408/c879f182-6f70-43b0-b808-0aec757595f9)

**Comment by Jack-Chronicle** [comment]
Had the same issue today, may want to check your snippets to see if any of them could be causing this. Had one that changed the background color (not sure why it did) but removing that line from it fixed this issue and didn't mess with the snippet afterwards either

Although given that more people have had this error as well, this is likely just a bandaid fix for now

**Comment by amatya-aditya** [comment]
Turning off all the snippets did not resolve the issues. The default theme functions normally, but there is interference when using the Minimal and AnuPpuccin themes.

**Comment by Superschnizel** [comment]
@amatya-aditya I just released Version 1.0.6 wich should hopefully resolve most of the issues with the rendering of special elements.
If you have the time please check out the new version and let me know if the issues persist.

**Comment by amatya-aditya** [comment]
@Superschnizel The new update solved the issues for me. Thanks ❤️
