### ISSUE TITLE
[Bug ?] Plugin affects dataview tables & js inline code 

### ISSUE THREAD

**Issue by Tanjamuse** [Superschnizel/obisdian-fast-text-color#11]
Hi.

The plugin looks super interesting, but unfortunately it affects both dataview tables and js inline code. I have tried it with both minimal theme and with the default. I have also disabled all css snippets, and it still happens.

This is what happens with the plugin enabled:
![fast color enabled](https://github.com/Superschnizel/obisdian-fast-text-color/assets/15678057/d0c95224-9c33-4a33-9598-4504f744f339)

And this is what it is supposed to look like:
![fast color disabled](https://github.com/Superschnizel/obisdian-fast-text-color/assets/15678057/ab0aaeaf-ae29-4bc2-9dd0-b30229fc78f9)

Thanks so much in advance

**Comment by Superschnizel** [comment]
@Tanjamuse I just released Version 1.0.6 wich should hopefully resolve most of the issues with the rendering of special elements.
If you have the time please check out the new version and let me know if the issues persist.

**Comment by Tanjamuse** [comment]
The only change I can see is that now the background is black instead of greyed out. It still interferes with dataview (both the table and the js snippet that counts pages based on tags) as well as the icon above the "Tester" heading.

![ftc](https://github.com/Superschnizel/obisdian-fast-text-color/assets/15678057/1391e479-7d65-42d1-976d-3354cc3752e9)

**Comment by Superschnizel** [comment]
would you be able to share the js snippet and the note so i can try to recreate this issue?

**Comment by Tanjamuse** [comment]
There is no js snippet other than the text on the page, but here it is

[Image Test Dataview.md](https://github.com/user-attachments/files/16140060/Image.Test.Dataview.md)

I have the following plugins installed:

Base Tag renderer
Colored text
Commander
Creases
Dataview
DB Folder
File Color
Folder Notes
Hide Folders
Home Page
Icon Short codes
Minimal theme settings (Which is also the theme I'm using)
Pinned Notes
Plugin Update Tracker
Refresh Preview
Set View Mode Per Note
Settings Search
Style Settings
Style Settings
Templater

I have tried with several different pages with dataview tables or lists and it doesn't matter which one I use, all I can see is that line of text that says:

`Loading ...`

Thanks in advance
