### ISSUE TITLE
[Bug] Messes with Rendering of certain elements

### ISSUE THREAD

**Issue by Jack-Chronicle** [Superschnizel/obisdian-fast-text-color#12]
**Describe the bug**
When used with the Iconize or Icon Shortcodes Plugin, the icons stop rendering correctly
Icon Shortcodes obsidian icons stop rendering at all
And all icons stop rendering for both plugins when their are more than 3 sets of backticks, and at two sets the second pair will start having issues anyways

**To Reproduce**
1. Enable Icon Shortcodes or Iconize (Or both)
2. Add an Icon to a line in any File
3. See First Error (No obsidian icons)
4. Add more than two backticked text lines
5. See Second Error

**Expected behavior**
The plugin shouldn't cause errors for either scenario

**Screenshots**
![Iconize + Color](https://github.com/Superschnizel/obisdian-fast-text-color/assets/18507378/839acdd3-7900-412c-b8fa-e86d4c67faae)
![Shortcodes + Color](https://github.com/Superschnizel/obisdian-fast-text-color/assets/18507378/a6f61feb-0e02-4d04-8548-2b9a4dc38b95)
![No Color](https://github.com/Superschnizel/obisdian-fast-text-color/assets/18507378/8e76f230-dfa4-4daf-b089-5f3a501dc9fc)

**Comment by Jack-Chronicle** [comment]
Just Found another issue, it's cutting off the edges of the sidenotes snippet, and prevents opening/closing of callouts

(Really like this plugin's concept and design so I'm gonna keep looking for bugs if you don't mind that)

![Fast Color](https://github.com/Superschnizel/obisdian-fast-text-color/assets/18507378/e87b9098-8f7c-4bbf-9a92-351fe16b5098)
![No Fast Color](https://github.com/Superschnizel/obisdian-fast-text-color/assets/18507378/c5eae650-20cf-434e-ac37-c679f004d867)

**Comment by Superschnizel** [comment]
This seems to be related to #9 #10 #11. There is a bug that causes interference with the css of other plugins, i hope i will e able to fix it soon.

**Comment by Jack-Chronicle** [comment]
Hope you're able to fix it smoothly, cause this is a great plugin otherwise

**Comment by Superschnizel** [comment]
@Jack-Chronicle I just released Version 1.0.6 wich should  hopefully resolve most of the issues with the rendering of special elements.
If you have the time please check out the new version and let me know if the issues persist.

**Comment by Jack-Chronicle** [comment]
I'm not seeing any of the previous issues I had, seems to be working much better now. Thanks!
