### ISSUE TITLE
Tabs are not compatible with the plugin "Fast Text colors"

### ISSUE THREAD

**Issue by Flexit07** [Superschnizel/obisdian-fast-text-color#15]
**Version**
1.1.1

**Describe the bug**
Once the plugin "Fast Text Colors" is present, "Tabs" stop to work

**To Reproduce**
Simply disable and enable many times that plugin and watch. If FTC is on "Tabs" doesn't work, if FTC is off "Tabs" is OK

**Comment by Superschnizel** [comment]
Can you descibe the Problem in a bit more detail? What do you mean by "Tabs", can you not change tabs in the workspace anymore or are you refereing to a different functionality?

**Comment by Flexit07** [comment]
Sorry, I realized now that, doing things a little bit in hurry I posted this feedback in the wrong place. It's a bug that involves another plugin, "Tabs" that stops to work when Fast Text Colors is activated. But Fast Text Colors, by itself, works perfectly all the time. I will share this problem in the right place, hope you forgive me

**Comment by Superschnizel** [comment]
I think that this is still an issue on this Plugin. I am currently working on a Bug that causes interactive objects to longer be interactable, see #13 for example.

**Comment by Superschnizel** [comment]
@Flexit07 I created a new Version with an improved rendering method, that will hopefully deal with these issues. Because i am still unsure about the stability i would like to test it a bit further you have to enable the reworked rendering in the settings.

Please try out the new rendering and tell me if your issues are resolved.

**Comment by Flexit07** [comment]
I have checked right now the compatibility between the two plugins several times and it seems that the problem has been solved!
Thank you for your efforts and your availability!

**Comment by Flexit07** [comment]
I'm sorry to tell you that I've just discovered another bug.

Coloring some text with your plugin inside a callout (native plugin of Obsidian) is not possible expand or collapse it anymore

**Comment by Superschnizel** [comment]
Can you send me an example where this happens? This issue should have been also resolved with the new rendering method as it was previously mentioned here #13

**Comment by Flexit07** [comment]
Your plugin v. 1.0.72 had this problem:


`> [!note]+
> 
>This is a callout that expand and collapse


> [!note]+
> 
>~={yellow}This is a callout that doesn't expand neither collapse=~
`

but your upgraded to 1.0.73 has solved it too, thanks!
