### ISSUE TITLE
[Bug] themes (editing and adding your own)

### ISSUE THREAD

**Issue by Tanjamuse** [Superschnizel/obisdian-fast-text-color#19]
Hi

I use the most recent version, and maybe it's me who has misunderstood something, but I expected it to behave differently with the themes. What I expected it to do was, when I create a new theme, it would give me a "blank slate" to add my custom colors to, and that the new custom colors would be "confined" to that theme alone.

Instead this is what happens: when I add a custom theme and then add a color to that it is shown in both themes and subsequently deleted in both themes too. As shown by the two screenshots below.

I have tried this in both default and minimal theme, and the same thing happens.

![Test theme](https://github.com/user-attachments/assets/a03dbf12-6104-4cf4-82af-f355423ff8c0)
![Default theme](https://github.com/user-attachments/assets/e030fccc-94d6-4ce1-a407-3f7138d23e9a)

Thank you so much in advance.

**Comment by Superschnizel** [comment]
Hi @Tanjamuse i just released version 1.0.71 which contains a hotfix for the handling of the settings.

Please try it out and let me know if there are still any issues.

**Comment by Tanjamuse** [comment]
As far as I can tell, it works now. And again, thank you so much for the work you do and with the speed you manages these fixes.

**Comment by Tanjamuse** [comment]
Although I can't delete the test theme and any icons added to the text no longer shows up correctly as soon as I change a note from preview mode to read mode, unless they are emojis. If they are luc icons or the custom icons added in the Icon Shortcodes plugin they get changed to text, as shown in my screenshot below.

Preview mode: ![preview mode](https://github.com/user-attachments/assets/93f0da7b-9f82-43fa-9551-8f2c4e2722db)
Read mode: ![read mode](https://github.com/user-attachments/assets/f93b379e-dba8-4740-8e4e-18af1a9fafef)

**Comment by Superschnizel** [comment]
@Tanjamuse, it seems there was still an issue regadrding the theme deletion. It should be fixed with version 1.0.72.

The other problem regarding the icons seems to be related to the issues with the postprocessing rendering. Do you have the Experimental rendering enabled in your settings? If so then this problem should probably be a new issue.

**Comment by Tanjamuse** [comment]
Shit I'm so sorry, you are absolutely right, that should've been a separate thread, I have checked, and the new version makes deleting the themes I no longer want to see possible, which is why I'm closing this, and opening a new one for the icon-problem.

Thank you again, for your patience and your good work.
