### ISSUE TITLE
[Bug] icon trouble

### ISSUE THREAD

**Issue by Tanjamuse** [Superschnizel/obisdian-fast-text-color#20]
Any icons added to the colored text no longer shows up correctly as soon as I change a note from preview mode to read mode, unless they are emojis. If they are luc icons or the custom icons added in the Icon Shortcodes plugin they get changed to text, as shown in my screenshot below. This also happens when there are icons in the text that follows a line or word that has been colored.

The first screenshot is preview mode, and the second is read mode.

![preview mode](https://github.com/user-attachments/assets/4c135323-ef31-4c32-9524-8e391978aff3)
![read mode](https://github.com/user-attachments/assets/b288ce47-822b-49fc-b59b-e4d218c0833d)

**Comment by Superschnizel** [comment]
Hi @Tanjamuse , i am having trouble recreating this issue. Do you have "Use node rebuilding (EXPERIMENTAL)" enabled in the settings?

**Comment by Tanjamuse** [comment]
No, I haven't enabled that. The only two I have enabled is 

Interactive delimeters 

and

Use keybindings

I have several other plugs-ins enabled:

Base Tag renderer
Colored text
Commander
Creases
Dataview
DB Folder
File Color
Folder Notes
Hide Folders
Home Page
Icon Short codes
Minimal theme settings (Which is also the theme I'm using)
Pinned Notes
Plugin Update Tracker
Refresh Preview
Set View Mode Per Note
Settings Search
Style Settings
Style Settings
Templater

**Comment by Superschnizel** [comment]
Try enabling this feature, it will hopefully resolve issues related to faulty rendering in reading mode. It is currently in testing, but i plan on making it the default soon.

**Comment by Tanjamuse** [comment]
That did the trick, thank you so much again, I am very much looking forward to seeing what else you have in store for this plugin.

**Comment by Tanjamuse** [comment]
I don't know what happened, but this no longer works, and yes I still have the "Use node rebuilding (EXPERIMENTAL)" enabled. I've also tried disabling it, and that doesn't make it work either.
