### ISSUE TITLE
[Feature Request] Canvas Support

### ISSUE THREAD

**Issue by AndyLiu9** [Superschnizel/obisdian-fast-text-color#30]
Canvas render support

**Comment by Superschnizel** [comment]
@AndyLiu9 Can you describe this in more Detail? What exactly are you missing in canvas support? For me the plugin works as expected in the Canvas.

**Comment by AndyLiu9** [comment]
Hi, sorry for that. I relauched obsidian and now it works in canvas. Thanks!
