### ISSUE TITLE
[Bug] interactive delimeter not working with more than 8 colours

### ISSUE THREAD

**Issue by JannikWilhelm** [Superschnizel/obisdian-fast-text-color#34]
**Version**
1.1.1

**Describe the bug**
When using 8 or less colours in the theme, the interactive delimeter does not appear while hovering over the colour symbol in the editor. 

**To Reproduce**
1. have 8 or less colours in the active theme
2. in the editor, add coloured text and hover over the delimeter to edit the colour. The menu appears
3. add more colours, so you have 9 in the theme
4. repeat step 2. The menu does not appear

**Expected behavior**
The menu (interactive delimeter) should appear, even with more than 8 colours

**Screenshots**
8 Colours only, menu working ![only 8 colours](https://github.com/user-attachments/assets/4d9110dc-8092-440e-804c-daa480f7dac1)

9 colours, no menu appearing ![9 colours](https://github.com/user-attachments/assets/6a9c49e0-a6f6-47af-9d76-642fb9788ff2)  ![9 colours](https://github.com/user-attachments/assets/c117e45a-2ee1-480c-bdce-674363265e71)

**Comment by aliceinblunderland0** [comment]
![image](https://github.com/user-attachments/assets/ed6999dd-6d5b-4db3-a2c1-3c9a45698e57)
Something that's probably related to this error is the bar showing the hotkeys. Despite the box stretching to fit many squares, the display ends at 10. Tested this in a sandbox vault, as well.

**Comment by JannikWilhelm** [comment]
This behaviour now does not happen for me as well, so some Update might have resolved this.
