### ISSUE TITLE
The repo is called "obisdian-..." instead of "obsidian-..."

### ISSUE THREAD

**Issue by FlamingFire0** [Superschnizel/obisdian-fast-text-color#40]
(Title)
![image](https://github.com/user-attachments/assets/eed64966-4e3f-40c4-abef-c8ffa5302da2)

Just rename it

**Comment by Superschnizel** [comment]
See #22 . I have to check if this will cause any Problems with the obsidian Plugin Browser.

**Comment by FlamingFire0** [comment]
> See #22 . I have to check if this will cause any Problems with the obsidian Plugin Browser.

Yea, I saw that after I sent the issue, you can delete this issue
I am pretty sure there are no problems in the plugin browser, because the plugin worked perfectly fine for me
