### ISSUE TITLE
[Bug] does not work in Obsidian v1.6

### ISSUE THREAD

**Issue by mr-d-r** [Superschnizel/obisdian-fast-text-color#5]
Thank you for the great extension!
It is exactly what I was looking for!

Unfortunately in Obsidian v1.6 error appears
plugin:fast-text-color:873 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'version')
    at FastTextColorPlugin.loadSettings (plugin:fast-text-color:873:22)
    at async FastTextColorPlugin.onload (plugin:fast-text-color:810:5)
so plugin does not work.

As a workaround I've just commented out the following lines:
    if (+rawSettings.version < +SETTINGS_VERSION) {
      console.log("outdated Settings! Trying to update.");
      this.settings = updateSettings(rawSettings);
      await this.saveData(this.settings);
      return;
    }

Please fix when you have some time.

Appreciated in advance

**Comment by Superschnizel** [comment]
This is fixed in version 1.0.4

**Comment by mr-d-r** [comment]
thank you for the fast reply.
obsidian had installed the old version.
now it is 1.0.5 and works fine!
