### ISSUE TITLE
[Bug] Plug-in interferes with outline sidebar

### ISSUE THREAD

**Issue by DutchPete** [Superschnizel/obisdian-fast-text-color#7]
This is a great plug-in; unfortunately I cannot use it due to this bug.

**Describe the bug**
When I color text, the outline sidebar is affected.

**To Reproduce**
1. Create a new note
2. Add some headings, subheadings, and text
3. Open the Outline sidebar on the right
4. Color some text using the plug-in
5. See effect on outline.

**Expected behavior**
Outline remains unaffected.

**Screenshots**
*Outline prior to text coloration:*

![image](https://github.com/Superschnizel/obisdian-fast-text-color/assets/10794265/f5e85665-8c02-4ae8-8747-0d1f6c3ca15b)

*Outline after text coloration:*
![image](https://github.com/Superschnizel/obisdian-fast-text-color/assets/10794265/08f5ed22-c830-48d1-9e6e-23b0b1b16d8e)

**Additional context**
Semi-workaround:

1. Color the text using the plug-in
2. Observe the changed outline
3. Disable the plug-in
4. Reload Obsidian (Cmd+R / CTRL+R)
5. Outline is back to normal
6. Re-enble the plug-in: Outline will not be affected

However, whenever one reloads Obsidian with the plug-in enable, the Outline will be messed up again.

**Comment by Superschnizel** [comment]
Hi, thanks for the report.

I am not able to reproduce this issue in my vault. Maybe something else is causing a bad interaction:
- Are you using a plugin or snippet that affects the style of the outline?
- What theme are you using?
- Is the ABC in the second image added when there is colored text in the note?

Thanks for taking the time.

**Comment by DutchPete** [comment]
Hello Leon, thanks for your quick reply. I have found the culprit: a plug-in called Outline++.
So, this is not a bug, it is interference of another plug-in.
My apologies for calling this a bug and not checking my other plug-ins first. In any case, if someone ever complains about this, you know why 😀
