### ISSUE TITLE
[Bug ?] Interference with tables

### ISSUE THREAD

**Issue by DutchPete** [Superschnizel/obisdian-fast-text-color#9]
**Describe the bug**
As the saying goes, *a picture is worth 1000 words*, so here goes:

Original table:

![image](https://github.com/Superschnizel/obisdian-fast-text-color/assets/10794265/1f6fc8c4-7078-4817-8fe1-f36850802906)

After enabling your plug-in:

![image](https://github.com/Superschnizel/obisdian-fast-text-color/assets/10794265/b8aaf7c3-b589-434a-bba6-6fdae80eb415)

I have no table-related plug-ins, and am using the ITS theme.

I tried with another theme, Kakano, and the effect is the same:

Before

![image](https://github.com/Superschnizel/obisdian-fast-text-color/assets/10794265/edde4e00-8c07-40de-8cba-c582535ecbf3)

After

![image](https://github.com/Superschnizel/obisdian-fast-text-color/assets/10794265/349ac405-2801-4963-880e-577d82bba125)

**Expected behavior**
No difference in table rendering between the enabled and disabled status of the plug-in.

**Comment by Superschnizel** [comment]
@DutchPete I just released Version 1.0.6 wich should hopefully resolve most of the issues with the rendering of special elements.
If you have the time please check out the new version and let me know if the issues persist.

**Comment by DutchPete** [comment]
Yes, the issue is resolved! Many thanks for your help.

**Comment by aliceinblunderland0** [comment]
If anyone else runs into this problem despite the updates, the [Sheets Extended](https://github.com/NicoNekoru/obsidan-advanced-table-xt) plugin was the culprit for me. That plugin doesn't work with Obsidian's new tables, anyways, so it was gathering dust in my vault....
